# Base image with Python 3.10
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Create the required directories for output and temp files
RUN mkdir -p /app/output/detected_items /app/temp

# Copy the project files
COPY . /app

# Copy the environment file
COPY .env /app/.env
# Debugging step: Print environment variables
RUN printenv | grep GOOGLE_API_KEY

# Copy the model weights into the container
COPY runs/detect/train7/weights/best.pt /app/runs/detect/train7/weights/best.pt

# Copy the Streamlit assets into the container
COPY streamlit/assets /app/streamlit/assets

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose Streamlit's default port
EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.enableCORS=false"]
